title: Little Hearts Learning Centre
description: Creating enabling spaces to realize the educational and functional needs of children
url: "https://cortinarius-i.github.io"
baseurl: "/LHLC_deCAP"

markdown: kramdown
permalink: pretty

collections:
  programs:
    output: true
    permalink: /programs/:name/
  activities:
    output: true
    permalink: /activities/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page
