title: Little Hearts Learning Collective
description: Cozy, curiosity-led learning
url: "https://cortinarius-i.github.io"
baseurl: "/LHLC_deCAP"

markdown: kramdown

collections:
  programs:
    output: true
    permalink: /programs/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page
